# Generated by Django 3.0.3 on 2021-01-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_producttags'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnails',
            field=models.ImageField(null=True, upload_to='product-thumbnails'),
        ),
    ]
