# Generated by Django 3.0.3 on 2021-01-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productimage_thumbnails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='thumbnails',
            new_name='thumbnail',
        ),
    ]
